name: moorsyl
version: 1.0.0
description: Moorsyl API client for Dart and Flutter
homepage: https://docs.moorsyl.com
repository: https://github.com/SoftwareSavants/moorsyl-dart

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: '^5.2.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0
